### ISSUE TITLE
Use alternatives to nodejs modules

### ISSUE THREAD

**Issue by superguineapig** [cschwarz/wkx#21]
Hello there!

First, let me say thanks and I love the wkx package! It works great.

One thing I ran across recently was that wkx will not compile in a react-native based project. As far as I can tell, it looks like this is due to the use of `util.inherits` and `Buffer` The react-native ecosystem does not support any nodejs runtime modules, in this case the _util_ module and the _Buffer_ built-in.

So I was wondering if you would be willing to swap out the node stuff for more portable alternatives like [node-util-inherits](https://github.com/kaelzhang/node-util-inherits) and [buffer](https://github.com/feross/buffer) instead?

If not, I suppose I could fork wkx, but it seems like a change that might benefit others as well without creating a separate repo.

Anyway, thanks for all the great work.

**Comment by cschwarz** [comment]
Hey, I am not really familiar with react-native, but have you looked into using https://github.com/tradle/rn-nodeify?

**Comment by superguineapig** [comment]
Unfortunately, for me, the magic that rn-nodeify (and others) performs is a no-go with my setup. In general, the react-native build/package environment is extremely sensitive to changes in dependencies.

I think my only option at this point is to attempt to modify a local fork of wkx in my project, and see if I can replace the node specific stuff wholesale without resorting to shims or additional transpiler magic.

**Comment by kylebarron** [comment]
Would there be interest in a PR to use an [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) instead of a Node `Buffer`? The `ArrayBuffer` is natively supported in browser JS, and Node [`Buffer` instances are also `Uint8Array` instances](https://nodejs.org/docs/latest/api/buffer.html#buffer_buffers_and_typedarrays) and thus are instances of an `ArrayBuffer`.

This means that switching to using `ArrayBuffer` would allow use everywhere without complications. Comments?

**Comment by superguineapig** [comment]
@kylebarron It's been a long time since I first encountered this, but if I recall, the way in which `Buffer` is being used is for bit-level stuff and endian-ness.

I don't think that stuff is available on the superclass `Uint8Array`

My first thought is that the trick would be to re-implement the `Buffer` specific  `read*` and `write*` functions on top of `Uint8Array` (or maybe even larger typed arrays?) used here:

https://github.com/cschwarz/wkx/blob/b85b7b93af101a87a7a0fffa2a6d68c551b3f8d3/lib/binaryreader.js#L24-L31

and here:

https://github.com/cschwarz/wkx/blob/b85b7b93af101a87a7a0fffa2a6d68c551b3f8d3/lib/binarywriter.js#L18-L31

Not sure what kind of effort that would be in plain JS, as I think the `NodeJS` version actually does that stuff in `C` as a native module.  Would need to pass all the same unit tests that Buffer does though. Probably a big lift.

*Disclaimer*: It's just my $0.02 though. I am definitely not an expert on this lib :-) I have moved on from the project I was working on when I first submitted this issue. And to get back to the original question: sure, I'd be interested to see if what you suggest could be done.

**Comment by kylebarron** [comment]
> I don't think that stuff is available on the superclass `Uint8Array`

Correct, but it is available as a [_`DataView`_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView), which is a class you can create from a raw `ArrayBuffer` that enables reading and writing bytes at the byte level, taking into account data type and endianness.

I was actually just implementing this for another project. It looks like this when writing:
```js
const view = new DataView(arrayBuffer);
// littleEndian is a boolean
view.setFloat64(offset, value, littleEndian);
```

Essentially the `DataView` is almost a drop-in replacement for the custom `BinaryReader` and `BinaryWriter`. I haven't attempted modifying this package, and will probably wait until hearing from the maintainer, but at first glance I would expect it to be relatively easy.

**Comment by superguineapig** [comment]
Oh yeah, DataView! That's really cool. Compatibility table looks pretty good too. Seems relatively well supported now. Armed with this, it might be relatively simple to reimplement the classes in question.

Thanks for mentioning it. I might just have a use case for it in my current projects as well.

**Comment by jayarjo** [comment]
@superguineapig @kylebarron would you mind to make a PR for this?

**Comment by jayarjo** [comment]
Actually there're instructions for usage in the browser here: https://github.com/cschwarz/wkx#browser. So my question now is, if browsers are supported, why is this issue still open?

**Comment by superguineapig** [comment]
@jayarjo My personal reason for filing this back in 2018 was that Browserify shims nodejs Buffer with https://github.com/feross/buffer
which at the time was woefully out of date with current node implementation. There was (still is) a bug with the alternate version of Buffer that would not allow wkx's unit tests to pass. I had filed a report with the folks over there https://github.com/feross/buffer/issues/197
but it still remains open to this day.

Since it's been several years, I have moved on from the project I was working on at the time, and haven't had a chance to revisit the original (this) issue. (that was a React Native project)

My exchange with @kylebarron was really intriguing, and I suspect that it might be possible to completely remove the need to use browserify, however I simply haven't had any time to look into Kyle's suggestion either.

I'm happy to close this out if it's no longer of interest to anyone, or if @cschwarz doesn't want any modifications to wkx (after all, my react-native use case wasn't really in the scope of this repo), but I'm also happy to help review PRs if they come along.

cheers!

**Comment by kylebarron** [comment]
My motivation was just that with modern JS there should be no need to polyfill _NodeJS classes in the browser_, if anything should be vice versa, so that bundle sizes are smallest for the browser. (Bundle size doesn't matter much for Node dependencies). Given that all modern browsers support `TypedArray`s and `DataView`s, there should also be maximum performance by using those directly.

I didn't make a PR to `wkx` because in the end it was simplest for [`loaders.gl`](https://loaders.gl/)'s purposes to simply [redo WKB decoding](https://github.com/visgl/loaders.gl/pull/775/files#diff-31f27ebe2c237e7f357deeebf930ec2c7865fc9c5ec3249616038f28f0580663). This is especially true because in `loaders.gl` we support decoding to both GeoJSON _and_ a binary format, which is more performant in WebGL applications (and faster to decode when the data starts as binary). We decided that it was simplest to write a new parser for WKB using modern JS rather than try to create a PR here.

**Comment by jayarjo** [comment]
> because in the end it was simplest for [`loaders.gl`](https://loaders.gl/)'s purposes to simply [redo WKB decoding](https://github.com/visgl/loaders.gl/pull/775/files#diff-31f27ebe2c237e7f357deeebf930ec2c7865fc9c5ec3249616038f28f0580663). This is especially true because in `loaders.gl` we support decoding to both GeoJSON _and_ a binary format, which is more performant in WebGL applications (and faster to decode when the data starts as binary). We decided that it was simplest to write a new parser for WKB using modern JS rather than try to create a PR here.

Oh, wow. Basically WKB parser is the only part that I really require in our app as well. Why don't you publish it as a separate module? Is it ok to grab and adapt it? Keeping the license of course.

**Comment by kylebarron** [comment]
> Why don't you publish it as a separate module?

It is a separate module: `@loaders.gl/wkt`, and it supports code-splitting. [Usage](https://github.com/visgl/loaders.gl/blob/master/modules/wkt/docs/api-reference/wkb-loader.md#usage). Note you might need to combine with [`binaryToGeoJson`](https://github.com/visgl/loaders.gl/blob/master/modules/gis/src/lib/binary-to-geojson.js) from `@loaders.gl/gis` because the `WKBLoader`'s default output is currently only [our binary format](https://github.com/visgl/loaders.gl/blob/master/modules/gis/docs/api-reference/geojson-to-binary.md#outputs).

**Comment by superguineapig** [comment]
Guess it makes sense to close this now.
