### ISSUE TITLE
How to parse a generic geometry blob to GeoJSON?

### ISSUE THREAD

**Issue by tsemerad** [cschwarz/wkx#26]
My application has a GeoPackage with a feature table that holds a variety of geometry types. I use wkx to parse my geometry blob, so I can convert it to GeoJSON:

```javascript
wkx.Geometry.parse(r.geom);
```

But it gives me the following error:
```
Error parsing geom blob: Error: GeometryType 0 not supported
```

`GeometryType 0` references the generic Geometry data type since my GeoPackage feature table has mixed geometry types. Is it possible for this library to support parsing the generic Geometry type?

If not, is it possible for me to explicitly tell wkx the type when it's parsing it? Something like:
```javascript
wkx.Geometry.parse(r.geom, "Point");
```

**Comment by IanKemp** [comment]
As far as I can see from my brief scan of the GeoPackage format, it stores its geometry in standard WKB format, which encodes the actual type of that geometry (Point, LineString, etc.). Thus there is no need to explicitly tell a parser what you are expecting.

`GeometryType 0 not supported` means WKX tried to parse the geometry type from what you provided, and got 0 which is not a valid geometry type. There are two reasons why this can happen:

* Your WKB is encoded incorrectly (doubtful, as the GeoPackage/SQLite format would catch and disallow that)
* You've encountered a bug in WKX's parsing

Based on my own recent experiences with WKX, my guess would be the second option, but you would have to post an example of the geometry you're trying to parse to allow that to be confirmed.

**Comment by taviroquai** [comment]
@tsemerad @IanKemp 

GeoPackage uses a differente WKB structure that includes an envelop. I had a small discussion with the team that created the GeoPackage spec some time ago.

Please read at https://www.geopackage.org/ in section "FAQ" in question "Why does GeoPackage use a different Well-Known Binary (WKB) encoding than PostGIS or SpatiaLite?"

I stopped supporting GepPackage in my project because of too much hassle...

Anyway, I did a parse implementation in PHP here:
https://github.com/taviroquai/mapigniter2/blob/master/app/GeoPackage.php#L276

I hope it helps.

**Comment by tsemerad** [comment]
Thanks for the input. I temporarily had a workaround where I stored the GeoJSON as a separate column, which of course was not ideal, and hopefully a temporary solution. I have since decided to pursue a different route for my app that doesn't use GeoPackage or wkx, and instead queries Mapbox vector tiles using the Mapbox iOS and Android SDK.
